name: Convert DOCX to PDF

on:
  push:
    paths:
      - "*.docx"
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install LibreOffice
        run: sudo apt-get update && sudo apt-get install -y libreoffice

      - name: Check if DOCX File Exists
        run: ls -lah || echo "DOCX file not found!"

      - name: Convert DOCX to PDF
        run: libreoffice --headless --convert-to pdf --outdir . "New Microsoft Word Document.docx"

      - name: List Files After Conversion
        run: ls -lah

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: converted-pdf
          path: "*.pdf"
